### ISSUE TITLE
New folder structure like more familiar to currents php frameworks

### ISSUE THREAD

**Issue by gnovaro** [INTisp/INTisp#20]
# New proposed structure
/webister/website -> /webister/public
/webister/interface -> /webister/app (is an application folder. I think it gives an erroneous interpretation of what the directory contains)

Move folders (Only expose through the public folder of the server an index file and static content of the assets (js / css / images)
/webister/interface/css -> /webister/public/asset/css
/webister/interface/js -> /webister/public/asset/js
/webister/interface/img -> /webister/public/asset/img
/webister/interface/images -> /webister/public/asset/img

**Comment by alwaysontop617** [comment]
I will continue to work on this project.

**Comment by alwaysontop617** [comment]
This issue has been fixed already.
