### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by Dexxa1024** [INTisp/INTisp#27]
I've installed it on ubuntu 16.04 and it installs, but cant login,  it says in ssh

 ####  Installation Done  ####
chmod: cannot access 'ftpserver': No such file or directory
chmod: cannot access 'miniserv': No such file or directory
chmod: cannot access 'intdaemon': No such file or directory
mv: cannot stat 'ftpserver': No such file or directory
mv: cannot stat 'miniserv': No such file or directory
mv: cannot stat 'intdaemon': No such file or directory
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
--2018-08-24 15:04:26--  https://ci.adaclare.com/job/IntISP%20Daemon/ws/restart.sh
Resolving ci.adaclare.com (ci.adaclare.com)... failed: Name or service not known.
wget: unable to resolve host address ‘ci.adaclare.com’
mv: cannot stat 'restart.sh': No such file or directory
make.sh: line 119: intdaemon: command not found
apache ALL=NOPASSWD: ALL
 == Creating www in /var/webister
 == Added admin.com succesfully! ==

The installation is now complete.
###############################################################################
You cannot start using IntISP until The daemon is running
Please update /etc/intdaemon/config.ini
With the correct MySQL Details
Then run the installer
After you run the installer type intdaemon start
Your system has installed IntISP 9
The default username and password is admin
Visit the control panel http://localhost/interface.
###############################################################################
How do i get this to work?

**Comment by Dexxa1024** [comment]
And i used 

sudo apt-get update && sudo apt-get install git make && git clone https://github.com/INTisp/INTisp.git && cd INTisp && sudo make

**Comment by alwaysontop617** [comment]
Due to some issues you will need to compile IntISP Daemon. Please visit your url /interface and tell me what it says

**Comment by alwaysontop617** [comment]
Also try running service apache2 start && service MySQL start

**Comment by Dexxa1024** [comment]
The interface page loads, when i try and login with username admin and pass admin it says invalid username and pass.  How do i compile the IntISP Daemon?

**Comment by Dexxa1024** [comment]
Domain http://yourpanel.n4t.co/interface/

I also noticed  

Resolving ci.adaclare.com (ci.adaclare.com)... failed: Name or service not known                                                                                                                                                             .
wget: unable to resolve host address ‘ci.adaclare.com’
--2018-08-24 16:43:54--  https://ci.adaclare.com/job/IntISP%20Daemon/lastSuccess                                                                                                                                                             fulBuild/artifact/build/intdaemon
Resolving ci.adaclare.com (ci.adaclare.com)... failed: Name or service not known                                                                                                                                                             .
wget: unable to resolve host address ‘ci.adaclare.com’
--2018-08-24 16:43:54--  https://ci.adaclare.com/job/IntISP%20Daemon/lastSuccess                                                                                                                                                             fulBuild/artifact/build/miniserv
Resolving ci.adaclare.com (ci.adaclare.com)... failed: Name or service not known                                                                                                                                                             .
wget: unable to resolve host address ‘ci.adaclare.com’
--2018-08-24 16:43:54--  https://ci.adaclare.com/job/IntISP%20Daemon/ws/requirem                                                                                                                                                             ents.txt
Resolving ci.adaclare.com (ci.adaclare.com)... failed: Name or service not known                                                                                                                                                             .

**Comment by Dexxa1024** [comment]
[OK] Add IonCube to PHP
[OK] Reboot Apache2        e2
 ####  Installation Done  ####
mkdir: cannot create directory ‘/etc/intdaemon’: File exists
chmod: cannot access 'ftpserver': No such file or directory
chmod: cannot access 'miniserv': No such file or directory
chmod: cannot access 'intdaemon': No such file or directory
mv: cannot stat 'ftpserver': No such file or directory
mv: cannot stat 'miniserv': No such file or directory
mv: cannot stat 'intdaemon': No such file or directory
Could not open requirements file: [Errno 2] No such file or directory: 'requirem                                                                                                                                                             ents.txt'
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
--2018-08-24 16:44:40--  https://ci.adaclare.com/job/IntISP%20Daemon/ws/restart.                                                                                                                                                             sh
Resolving ci.adaclare.com (ci.adaclare.com)... failed: Name or service not known                                                                                                                                                             .
wget: unable to resolve host address ‘ci.adaclare.com’
mv: cannot stat 'restart.sh': No such file or directory
make.sh: line 119: intdaemon: command not found
apache ALL=NOPASSWD: ALL
 == Creating www in /var/webister
mkdir: cannot create directory ‘/var/webister/80/cgi-bin’: File exists
 == Added admin.com succesfully! ==
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: N                                                                                                                                                             O)
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'

**Comment by alwaysontop617** [comment]
Send me an ssh details to dodiaraculus@outlook.com

**Comment by Dexxa1024** [comment]
I have sent you an email :-)

**Comment by alwaysontop617** [comment]
Upon further inspection, you need to type mysql -uroot -p
Enter the mysql password then type CREATE DATABASE webister;
Then visit http://yourpanel.n4t.co/interface/

**Comment by alwaysontop617** [comment]
When I did a git push i forgot to delete the data/register file

**Comment by alwaysontop617** [comment]
Once you are able to get into the panel I need to fix the daemon

**Comment by alwaysontop617** [comment]
Did it work?

**Comment by Dexxa1024** [comment]
cloudatacost had a error and deleted my cloud server, but it did get to the installation page,  but when it goes to https://adaclare.com/login/index/index.php?reg it wont let me register, just reinstalling the server again now

**Comment by alwaysontop617** [comment]
If it says awaiting activation. It means you should be getting a confirmation emaill

**Comment by Dexxa1024** [comment]
all it says is Oops, not sure what went wrong there!

**Comment by Dexxa1024** [comment]
Where can i find the data/register file to delete so i can get it back to the setup screen again?

**Comment by alwaysontop617** [comment]
Just type rm -rf /var/www/html/interface/data/register

**Comment by Dexxa1024** [comment]
I'm learning new stuff :-)

Thats all done, Just stuck on the activation but now as its not accepting anything i enter in the signup box on the website

**Comment by alwaysontop617** [comment]
Yea its actually a server issue
has nothing to do with intisp

**Comment by Dexxa1024** [comment]
By the looks of it i cant install it until i can activate it until the signups been fixed :-)

**Comment by alwaysontop617** [comment]
just for testing purposes, use the username testuser and password testuser

**Comment by alwaysontop617** [comment]
Did it work?

**Comment by Dexxa1024** [comment]
That worked :-)

**Comment by alwaysontop617** [comment]
Once the login is fixed, I will let you register.

**Comment by alwaysontop617** [comment]
Do you want to be a featured web host?

**Comment by Dexxa1024** [comment]
That would be nice :-)  im still working on my website at the moment, but i can email you my hosting's url if you would like me to

**Comment by alwaysontop617** [comment]
Well You are going to start having issues because I am probably going to fix some issues with our activation service. So when you start having issues please notify me. Thank You.

**Comment by alwaysontop617** [comment]
Please login to the intisp control panel and tell me what it says.

**Comment by alwaysontop617** [comment]
Are you there?

**Comment by alwaysontop617** [comment]
Im going to go ahead and close the issue as everything seems to be resolved.
